# Generated by Django 3.2.18 on 2023-04-23 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jun', '0006_question_click'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='click',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
